"""Initial database setup

Revision ID: 018c1283541c
Revises: 0cbbcc63372c
Create Date: 2024-11-04 08:44:23.004750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018c1283541c'
down_revision = '0cbbcc63372c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_options', schema=None) as batch_op:
        batch_op.create_index('idx_answer_options_question_id', ['question_id'], unique=False)

    with op.batch_alter_table('question_answers', schema=None) as batch_op:
        batch_op.create_index('idx_question_answers_quiz_id', ['quiz_id'], unique=False)

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index('idx_results_quiz_id', ['quiz_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.create_unique_constraint('users_email_key', ['email'])

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index('idx_results_quiz_id')

    with op.batch_alter_table('question_answers', schema=None) as batch_op:
        batch_op.drop_index('idx_question_answers_quiz_id')

    with op.batch_alter_table('answer_options', schema=None) as batch_op:
        batch_op.drop_index('idx_answer_options_question_id')

    # ### end Alembic commands ###
