"""Add correct_answer_text to QuestionAnswer model

Revision ID: 0cbbcc63372c
Revises: 3808ffecd9f7
Create Date: 2024-11-02 22:34:38.548795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbbcc63372c'
down_revision = '3808ffecd9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer_text', sa.Text(), nullable=False))
        batch_op.drop_constraint('question_answers_correct_answer_id_fkey', type_='foreignkey')
        batch_op.drop_column('correct_answer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('question_answers_correct_answer_id_fkey', 'answer_options', ['correct_answer_id'], ['id'])
        batch_op.drop_column('correct_answer_text')

    # ### end Alembic commands ###
