"""Add AnswerOption model and modify QuestionAnswer

Revision ID: 3808ffecd9f7
Revises: de0f809b8b5d
Create Date: 2024-11-02 22:19:47.850999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3808ffecd9f7'
down_revision = 'de0f809b8b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'answer_options', ['correct_answer_id'], ['id'])
        batch_op.drop_column('answer_text')
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('correct_answer_id')

    # ### end Alembic commands ###
