"""Initial migration

Revision ID: c59c0f1327ce
Revises: 
Create Date: 2024-11-04 08:56:33.270210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59c0f1327ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quizzes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes'))
    )
    op.create_table('question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_answer_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_question_answers_quiz_id_quizzes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_answers'))
    )
    with op.batch_alter_table('question_answers', schema=None) as batch_op:
        batch_op.create_index('idx_question_answers_quiz_id', ['quiz_id'], unique=False)

    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('attempt_date', sa.DateTime(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_results_quiz_id_quizzes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_results_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index('idx_results_quiz_id', ['quiz_id'], unique=False)

    op.create_table('answer_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_answers.id'], name=op.f('fk_answer_options_question_id_question_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_options'))
    )
    with op.batch_alter_table('answer_options', schema=None) as batch_op:
        batch_op.create_index('idx_answer_options_question_id', ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_options', schema=None) as batch_op:
        batch_op.drop_index('idx_answer_options_question_id')

    op.drop_table('answer_options')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index('idx_results_quiz_id')

    op.drop_table('results')
    with op.batch_alter_table('question_answers', schema=None) as batch_op:
        batch_op.drop_index('idx_question_answers_quiz_id')

    op.drop_table('question_answers')
    op.drop_table('quizzes')
    op.drop_table('users')
    # ### end Alembic commands ###
